### ISSUE TITLE
Feature: User and Admin Forms

### ISSUE THREAD

**Issue by bronight** [bronight/majaeks-heart#2]
# Epic Title

Feature: User and Admin Forms

## Epic Description

This feature will add user (Contact Us, Stay Informed) forms, and an admin (Upcoming Events Admin Form) form which will allow the user to enter information to reach out to Majaek's Heart admins, and allow the admins to update the Upcoming Events panel.

## List of Tasks

- [ ] Task 1: Contact Us form #3 
- [ ] Task 2: Stay Informed form #4 
- [ ] Task 3: Upcoming Events form #5
